/**
 * Stable Local LLM error codes.
 *
 * @since 2.0.0
 * @example
 * const code: LocalLLMErrorCode = 'LOCAL_LLM_NOT_AVAILABLE';
 */
export type LocalLLMErrorCode =
  | 'LOCAL_LLM_NOT_AVAILABLE'
  | 'LOCAL_LLM_DEVICE_NOT_ELIGIBLE'
  | 'LOCAL_LLM_NOT_ENABLED'
  | 'LOCAL_LLM_MODEL_NOT_READY'
  | 'LOCAL_LLM_MODEL_DOWNLOAD_REQUIRED'
  | 'LOCAL_LLM_CONTEXT_WINDOW_EXCEEDED'
  | 'LOCAL_LLM_CHAT_NOT_FOUND'
  | 'LOCAL_LLM_CHAT_BUSY'
  | 'LOCAL_LLM_GENERATION_NOT_FOUND'
  | 'LOCAL_LLM_GENERATION_CANCELLED'
  | 'LOCAL_LLM_INVALID_OPTIONS'
  | 'LOCAL_LLM_UNSUPPORTED'
  | 'LOCAL_LLM_IMAGE_NOT_READABLE'
  | 'LOCAL_LLM_IMAGE_TOO_LARGE'
  | 'LOCAL_LLM_GENERATION_FAILED'
  | 'LOCAL_LLM_IMAGE_GENERATION_FAILED'
  | 'LOCAL_LLM_UNKNOWN_ERROR';
